# Generated by Django 5.1.6 on 2025-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagwiseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='main_category',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='main_categories',
            field=models.ManyToManyField(related_name='main_bookmarks', to='tagwiseapp.category'),
        ),
    ]
