# Generated by Django 5.1.6 on 2025-03-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagwiseapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='screenshot_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
