# Generated by Django 5.1.6 on 2025-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagwiseapp', '0005_bookmark_screenshot_data_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='screenshot_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
