# Generated by Django 5.1.6 on 2025-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagwiseapp', '0015_register_apikey_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe')], default='en', max_length=2),
        ),
    ]
