# Generated by Django 5.1.6 on 2025-05-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagwiseapp', '0016_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
